version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: pg-docker
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
          - DATABASE_HOST=127.0.0.1
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    app:
        image:
        restart: always
        depends_on:
          - postgres
        