version: '3.7'
services:
    db:
      image: postgres:12.1-alpine
      container_name: pg-docker
      ports:
        - '5432:5432'
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/

    api:
      build: ./src
      command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
      container_name: coffee-api
      volumes:
        - ./src/:/usr/src/app/
      ports:
        - 8080:8000
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@db/postgres

volumes:
  postgres_data: